### ISSUE TITLE
migrationSet module not found

### ISSUE THREAD

**Issue by panuhorsmalahti** [olehch/oracle-migrate#5]
I get this error when trying to use the module locally:
```
pahorsma app $ node_modules/.bin/oracle-migrate help
module.js:471
    throw err;
    ^

Error: Cannot find module './migrationSet'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pahorsma/dev/app/node_modules/oracle-migrate/lib/tools.js:5:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Where is `migrationSet.js`?

I get the following error when trying to use the module globally:
```
pahorsma app $ oracle-migrate help
env: node\r: No such file or directory
```

**Comment by olehch** [comment]
Sorry, added that file in my latest commit

**Comment by panuhorsmalahti** [comment]
Thanks 👍
